# Root directory (defaults to current working directory if omitted)
base_dir: .

# Paths to Chrome and Chromedriver
chrome_path: chrome-mac-x64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing
chromedriver_path: chromedriver-mac-x64/chromedriver

# Output directories
output_dir: output

# Date range (inclusive start, exclusive end)
dates:
  start: "2025-08-01"
  end: "2025-09-01"

# Parallel scraping settings
num_workers: 8
